
package cn.bsoft.service.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ReadCardServerService", targetNamespace = "http://service.bsoft.cn/", wsdlLocation = "http://localhost:8888/service/?wsdl")
public class ReadCardServerService
    extends Service
{

    private final static URL READCARDSERVERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cn.bsoft.service.client.ReadCardServerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cn.bsoft.service.client.ReadCardServerService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8888/service/?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8888/service/?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        READCARDSERVERSERVICE_WSDL_LOCATION = url;
    }

    public ReadCardServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReadCardServerService() {
        super(READCARDSERVERSERVICE_WSDL_LOCATION, new QName("http://service.bsoft.cn/", "ReadCardServerService"));
    }

    /**
     * 
     * @return
     *     returns ReadCardServer
     */
    @WebEndpoint(name = "ReadCardServerPort")
    public ReadCardServer getReadCardServerPort() {
        return super.getPort(new QName("http://service.bsoft.cn/", "ReadCardServerPort"), ReadCardServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReadCardServer
     */
    @WebEndpoint(name = "ReadCardServerPort")
    public ReadCardServer getReadCardServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.bsoft.cn/", "ReadCardServerPort"), ReadCardServer.class, features);
    }

}
