
package cn.com.wsm.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "JavaServiceService", targetNamespace = "http://service.wsm.com.cn/", wsdlLocation = "http://10.41.109.41:8888/service/?wsdl")
public class JavaServiceService
    extends Service
{

    private final static URL JAVASERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cn.com.wsm.client.JavaServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cn.com.wsm.client.JavaServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://10.41.109.41:8888/service/?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.41.109.41:8888/service/?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        JAVASERVICESERVICE_WSDL_LOCATION = url;
    }

    public JavaServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JavaServiceService() {
        super(JAVASERVICESERVICE_WSDL_LOCATION, new QName("http://service.wsm.com.cn/", "JavaServiceService"));
    }

    /**
     * 
     * @return
     *     returns JavaService
     */
    @WebEndpoint(name = "JavaServicePort")
    public JavaService getJavaServicePort() {
        return super.getPort(new QName("http://service.wsm.com.cn/", "JavaServicePort"), JavaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JavaService
     */
    @WebEndpoint(name = "JavaServicePort")
    public JavaService getJavaServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.wsm.com.cn/", "JavaServicePort"), JavaService.class, features);
    }

}
